# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMRoleSeparationDutiesV1
metadata:
  name: iam-role-seperation-duties-kms
  annotations:
    description: Enforce separation of duties while assigning KMS related roles to users
spec:
  severity: high
  match:
    target: ["organizations/**"]
  parameters:
    assetTypes:
    - cloudresourcemanager.googleapis.com/Organization
    - cloudresourcemanager.googleapis.com/Folder
    - cloudresourcemanager.googleapis.com/Project
    roles: 
    - roles/cloudkms.admin
    - roles/cloudkms.cryptoKeyEncrypterDecrypter